# 6 Data Wrangling in Python

<div id="buttons">
<a class="btn btn-primary btn-lg" role="button" href="lectures/06_week.html">Lecture Slides (html)</a>
<a class="btn btn-secondary btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/lectures/06_week.ipynb">Lecture Slides (ipynb)</a>
<a class="btn btn-success btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/labs/06_week.ipynb">Lab Exercise (ipynb)</a>
<a class="btn btn-secondary btn-lg" role="button" href="labs/06_week.html">Lab Exercise (html)</a>
<a class="btn btn-danger btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/assignments/03_assignment.ipynb">Assignment</a>
</div>
---

This week we will turn from broader programming and software engineering concepts to practical approaches of working with data in Python. In particular, we will focus on `pandas`, a versatile library for data analysis, which often serves as the first building block in many data-science pipelines.

## Readings

- Guttag. Chapter 23
- McKinney. Chapters 5-9

## Lab

- Data input and output
- Working with pandas library

## Assignment 3

- Testing and data wrangling in Python
- Due at 11:00 on Wednesday, 27th October (submission on Blackboard)
- Rename the file from `03_assignment.ipynb` to `03_assignment_studentnumber_firstname_lastname.ipynb` before submission
