# 11 Complexity and Performance

<div id="buttons">
<a class="btn btn-primary btn-lg" role="button" href="lectures/11_week.html">Lecture Slides (html)</a>
<a class="btn btn-secondary btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/lectures/11_week.ipynb">Lecture Slides (ipynb)</a>
<a class="btn btn-success btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/labs/11_week.ipynb">Lab Exercise (ipynb)</a>
<a class="btn btn-secondary btn-lg" role="button" href="labs/11_week.html">Lab Exercise (html)</a>
<a class="btn btn-warning btn-lg" role="button" href="recordings/11_week_lecture.mp3">Recording</a>
<a class="btn btn-danger btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2021/blob/main/assignments/05_assignment.ipynb">Assignment</a>
</div>
---

Getting the correct result and having well-structured and documented code are only two aspects of a good program. We also want our code to execute fast and, in some cases, for it to finish running in a moment, hour, day, year, lifetime... This week we more formally discuss algorithmic complexity and performance. In addition to theoretical considerations we look into measuring execution time and benchmarking specific operations. 

## Readings

- Guttag. Chapters 11, 12;
- Wickham. Chapters [16: Performance](http://adv-r.had.co.nz/Performance.html), [17: Optimising Code](http://adv-r.had.co.nz/Profiling.html)

## Lab

- Analysis of function complexity and performance
- Timing and benchmarking

## Assignment 5

- Data wrangling and computational complexity
- Due at 11:00 on Monday, 29th November (submission on Blackboard)
- Rename the file from `05_assignment.ipynb` to `05_assignment_studentnumber_firstname_lastname.ipynb` before submission
